import { NextRequest, NextResponse } from "next/server";
import { auth0 } from "@/lib/auth0";
import { getRedis, isRedisConfigured } from "@/lib/db";
import { linkIdentityToPrimary } from "@/lib/account-link";
import { getMgmtToken } from "@/lib/federated-tokens";

export const dynamic = "force-dynamic";

const c = (v: string | undefined) => (v || "").replace(/[\r\n]+/g, "").trim();

const PROVIDER_MAP: Record<string, string> = {
  github: "github",
  slack: "sign-in-with-slack",
};

export async function POST(
  _request: NextRequest,
  { params }: { params: Promise<{ provider: string }> }
) {
  const session = await auth0.getSession();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { provider } = await params;
  const connection = PROVIDER_MAP[provider];

  if (!connection) {
    return NextResponse.json(
      { error: "Unknown provider" },
      { status: 400 }
    );
  }

  const currentSub = session.user.sub as string;

  // Store a one-time linking token that maps back to the current (primary) user.
  // After the social OAuth replaces the session with a new sub, PUT reads this token
  // to know exactly who the primary user is — no email matching needed.
  let linkingToken: string | undefined;
  if (isRedisConfigured()) {
    try {
      const redis = await getRedis();
      linkingToken = crypto.randomUUID();
      await redis.set(`link-tk:${linkingToken}`, currentSub, { ex: 600 }); // 10 min TTL
      await redis.del(`conn-status:${currentSub}`);
    } catch {
      // non-fatal — linking may fall back to email-based search
    }
  }

  const returnTo = linkingToken
    ? `/dashboard/connections?connected=${provider}&lt=${linkingToken}`
    : `/dashboard/connections?connected=${provider}`;
  const connectUrl = `/auth/login?connection=${encodeURIComponent(connection)}&returnTo=${encodeURIComponent(returnTo)}`;

  return NextResponse.json({ connectUrl });
}

// Called by the connections page after OAuth redirect-back to persist the mark.
export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ provider: string }> }
) {
  const session = await auth0.getSession();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { provider } = await params;
  const connection = PROVIDER_MAP[provider];
  if (!connection) {
    return NextResponse.json({ error: "Unknown provider" }, { status: 400 });
  }

  const userId = session.user.sub as string;
  const userEmail = (session.user.email as string | undefined)?.toLowerCase();

  // Read the one-time linking token generated by the POST handler before OAuth
  const body = await request.json().catch(() => ({})) as Record<string, unknown>;
  const linkingToken = body.lt as string | undefined;

  // ── Step 1: Persist connection markers (by sub AND by email).
  // Always write regardless of anything else — the OAuth did succeed
  // and the UI must show "Connected".
  const ex = 7 * 24 * 3600;
  if (isRedisConfigured()) {
    try {
      const redis = await getRedis();
      await Promise.all([
        redis.set(`conn-manual:${userId}:${connection}`, "1", { ex }),
        ...(userEmail
          ? [redis.set(`conn-manual:email:${userEmail}:${connection}`, "1", { ex })]
          : []),
      ]);
      await redis.del(`conn-status:${userId}`);
    } catch {
      // non-fatal
    }
  }

  // ── Step 2: Account linking — link this social identity to the primary user.
  //
  // Primary source: the one-time `link-tk` token written in POST before OAuth started.
  // This is 100% reliable — no email matching, no guessing.
  // Fallback: Management API email search (handles page refreshes / direct navigation).
  if (isRedisConfigured()) {
    try {
      const redis = await getRedis();

      // ── Primary: look up the token saved in POST
      let primarySub: string | null = null;
      if (linkingToken) {
        primarySub = await redis.get<string>(`link-tk:${linkingToken}`);
        if (primarySub) {
          await redis.del(`link-tk:${linkingToken}`); // single-use
          console.log(`[AccountLink] Resolved primary via linking token: ${primarySub}`);
        }
      }

      // ── Fallback: search Management API by email
      if (!primarySub || primarySub === userId) {
        let resolvedEmail = userEmail;
        if (!resolvedEmail) {
          const mgmtToken = await getMgmtToken();
          if (mgmtToken) {
            const res = await fetch(
              `https://${c(process.env.AUTH0_DOMAIN)}/api/v2/users/${encodeURIComponent(userId)}`,
              { headers: { Authorization: `Bearer ${mgmtToken}` } }
            );
            if (res.ok) {
              const profile = await res.json();
              resolvedEmail = (profile.email as string | undefined)?.toLowerCase();
            }
          }
        }
        if (resolvedEmail) {
          const mgmtToken = await getMgmtToken();
          if (mgmtToken) {
            const searchRes = await fetch(
              `https://${c(process.env.AUTH0_DOMAIN)}/api/v2/users?q=${encodeURIComponent(`email:"${resolvedEmail}"`)}&search_engine=v3`,
              { headers: { Authorization: `Bearer ${mgmtToken}` } }
            );
            if (searchRes.ok) {
              const allUsers = (await searchRes.json()) as Array<{
                user_id: string;
                identities?: Array<{ connection: string }>;
              }>;
              const other = allUsers
                .filter((u) => u.user_id !== userId)
                .sort((a, b) => (b.identities?.length ?? 0) - (a.identities?.length ?? 0));
              if (other.length > 0) {
                primarySub = other[0].user_id;
                console.log(`[AccountLink] Fallback: found primary via Mgmt API email search: ${primarySub}`);
              }
            }
          }
        }
      }

      if (primarySub && primarySub !== userId) {
        console.log(`[AccountLink] Linking ${userId} → primary ${primarySub}`);

        // Write marker under primary sub BEFORE linking so it survives the relogin
        await redis.set(`conn-manual:${primarySub}:${connection}`, "1", { ex });
        await redis.del(`conn-status:${primarySub}`);

        const result = await linkIdentityToPrimary(primarySub, userId);

        if (result.alreadyLinked) {
          // Already linked — no relogin needed, GET will show correct state
          console.log(`[AccountLink] Already linked, no relogin needed`);
        } else if (result.success) {
          await Promise.all([
            redis.del(`conn-status:${userId}`),
            redis.del(`conn-status:${primarySub}`),
          ]);

          // Force re-login via the primary connection (e.g. "github|155574376" → connection=github)
          const primaryPrefix = primarySub.split("|")[0];
          const primaryConnection =
            primaryPrefix && primaryPrefix !== "auth0" ? primaryPrefix : undefined;
          const reloginUrl = primaryConnection
            ? `/auth/login?connection=${encodeURIComponent(primaryConnection)}&returnTo=${encodeURIComponent("/dashboard/connections?linked=1")}`
            : `/auth/login?returnTo=${encodeURIComponent("/dashboard/connections?linked=1")}`;

          return NextResponse.json({
            ok: true,
            linked: true,
            needsRelogin: true,
            reloginUrl,
          });
        } else {
          console.warn(`[AccountLink] Link failed (non-fatal): ${result.error}`);
        }
      }
    } catch (e) {
      console.warn("[PUT] Account link check failed (non-fatal):", e);
    }
  }

  return NextResponse.json({ ok: true });
}
